### ISSUE TITLE
Cordova Gulp build task does not work properly on Windows

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture/boardz-cross-platform-sample#14]
...

[21:38:36] Starting 'cordova:build'...
cp: missing destination file operand after ‘..\resources" resources/’
Try 'cp --help' for more information.
WARNING: Applications for platform ios can not be built on this OS - win32.
Adding ios project...
iOS project created with cordova-ios@3.9.1
cp: no such file or directory: C:\Users\chris\Documents\GitHub\boardz-cross-platform-sample\cordova\resources\ios\icon\icon-60.png

...

**Comment by ThorstenHans** [comment]
May be the ending forward-slashes (see https://github.com/thinktecture/boardz-cross-platform-sample/blob/master/gulpTasks/cordova.js - Line 78 and 88 for example)

**Comment by ManuelRauber** [comment]
Valid point from @ThorstenHans 

Additionally a `sh.exec('cp...')` can not work at all on Windows. Using `gulp.src` now
