### ISSUE TITLE
Implement SignalR push scenario

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture/boardz-cross-platform-sample#17]
Some cool but useful use case... ;)

**Comment by ManuelRauber** [comment]
Why not socket.io?

**Comment by ChristianWeyer** [comment]
Erm... because our backend is .NET entirely :D

**Comment by ManuelRauber** [comment]
Well, I hoped, without looking further, that there is a socket io server for .net :)

**Comment by ChristianWeyer** [comment]
This is the reason why SignalR exists in the first place ;)

**Comment by ManuelRauber** [comment]
Hurray

**Comment by ManuelRauber** [comment]
This has been done for ng2-basta branch.
