### ISSUE TITLE
Exception in Cordova app on Windows 8/10

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture/boardz-cross-platform-sample#4]
SCRIPT5022: Unhandled exception at line 79, column 13 in ms-appx-web://net.tt.boardz/www/cordova.js
0x800a139e - JavaScript runtime error: module cordova/plugin_list already defined

If we remove the explicit <script src="cordova_plugins.js"></script>
from index.html manually everything works.

**Comment by ManuelRauber** [comment]
It seems that we don't need to add it explicitly. Cordova contains a method to load the cordova_plugins.js: https://github.com/apache/cordova-js/blob/master/src/common/pluginloader.js#L122
