### ISSUE TITLE
Extremely slow startup time with Cordova on device

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture/boardz-cross-platform-sample#46]
There is a long time of a white screen after the splash screen before the actual application shows up.
This can be seen on iOS, but is extremely slow and annoying on e.g. an Android Nexus 7 (2013).

BoardZ1 starts much faster - so this seems related to ng2.
We need to investigate and fix this.

**Comment by ThorstenHans** [comment]
bundle both `rxjs` and `angular2`

**Comment by ChristianWeyer** [comment]
😇
