### ISSUE TITLE
Do not use JS alerts as dialogs

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture/boardz-cross-platform-sample#49]
'Nuff said :)
Let's use Bootstrap dialogs.

**Comment by ManuelRauber** [comment]
Please specify where this happens.

**Comment by ChristianWeyer** [comment]
https://github.com/thinktecture/boardz-cross-platform-sample/blob/master/src/BoardZ/app/components/games/details.ts#L112

**Comment by ThorstenHans** [comment]
no native `alert` found. Perhaps @ManuelRauber closed it but he didnt associated the issue.
