### ISSUE TITLE
upgrade host.app to .NET Core 1.0

### ISSUE THREAD

**Issue by thinkrapido** [thinktecture/boardz-cross-platform-sample#55]
Would be really cool to see it working with the new .net

**Comment by ThorstenHans** [comment]
Also a valid point @thinkrapido perhaps @gingters can take this, because I know that he already did some great work with `core-1.0`? Not sure how his schedule looks like for the upcoming weeks. But I'll put it on the schedule

**Comment by ChristianWeyer** [comment]
We will most likely not move to .NET Core with this sample app. Sorry.
