### ISSUE TITLE
would be great to use the new router 3.0.0

### ISSUE THREAD

**Issue by thinkrapido** [thinktecture/boardz-cross-platform-sample#56]

**Comment by ThorstenHans** [comment]
Hey @thinkrapido, we will upgrade to the most recent router soon. I think we'll give the ng team time to publish another rc -> `rc5` before we'll migrate from `router-deprecated` to the most recent router implementation

**Comment by thinkrapido** [comment]
so cool. thumbs up.

**Comment by ThorstenHans** [comment]
router 3.0.0 has been integrated see 1db36f7916827c50be4d0e2b2d13d42dda9544d2
