### ISSUE TITLE
Rewrite NeedsAuthentication guard decorator

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture/boardz-cross-platform-sample#58]
We need to adhere to the new API after having moved to the new router.
https://github.com/thinktecture/boardz-cross-platform-sample/blob/ng-final/src/BoardZ/app/decorators/needsAuthentication.ts

**Comment by ThorstenHans** [comment]
`NeedsAuthentication` is gone `AuthGuard` is now responsible for protecting all necessary  routes.
