### ISSUE TITLE
Add angularfire2

### ISSUE THREAD

**Issue by cissecedric** [thinktecture/boardz-cross-platform-sample#61]
Hi,

I am struggling trying to add angularfire2 to this project, I get this error:
Error: Error: XHR error (404 Not Found) loading http://localhost:8000/angularfire2(…)

Is it currently possible to do this, or should I wait for an update?
Thanks,

**Comment by ManuelRauber** [comment]
Hi @cissecedric 

It seems, that you have not added angularfire2 to the build process. I've never used it, so I just guess, what you need to do to add it to your project.

If it is installed via `npm`, you need to add the dependency in the [gulp config](https://github.com/thinktecture/boardz-cross-platform-sample/blob/master/gulp.config.js#L79). Append an entry like `./node_modules/angularfire2/**/*`. Then you need to create a gulp task similar to the `[private-web]:copy-angular2-scripts` gulp task within [web.js](https://github.com/thinktecture/boardz-cross-platform-sample/blob/master/gulpTasks/web.js#L59), like this:

```
gulp.task('[private-web]:copy-angular2-scripts', function () {
            return gulp.src(config.source.files.angularfire2)
                .pipe(gulp.dest(path.join(config.targets.buildFolder, 'angularfire2')));
        });
```

Then you need to add this new task to the runSequence config shown [here](https://github.com/thinktecture/boardz-cross-platform-sample/blob/master/gulpTasks/web.js#L136)

Last but not least, you need to [configure SystemJS](https://github.com/thinktecture/boardz-cross-platform-sample/blob/master/src/BoardZ/system.setup.js#L16) to load angularfire2. You can do this by adding a mapping like

```
'angularfire2: 'angularfire2/bundles/angularFire2.umd.js'
```

After that, you can start the project again and angularfire2 should be able to load.

**Comment by cissecedric** [comment]
Great, it works!! (and I had to do the same with firebase),  
Thank you for your precises and detailed information. I wouldn't have found without it,
Regards,
